### ISSUE TITLE
Reorganizing the folder

### ISSUE THREAD

**Issue by snakedog116** [noname4444/smartthings#2]
Hello @noname4444!

First of all, thanks for creating the code for the monoprice smoke detector. I have 3 of these, and your code is a life-saver.

I'm just wondering if it would be possible for you to reorganize your folder structure to match Smartthings' recommended folder hierarchy. This would allow users like myself to quickly check for updates and sync them down to Smartthings from withing the Smartthings' API website.

I understand if that's not on your list of priorities, but it sure would be nice for people like myself using your code.

**Again, thanks!**

**Comment by snakedog116** [comment]
Another simpler option would be for you to just publish it to your 'SmartThingsPublic' folder. That'll put it in the right format

**Comment by noname4444** [comment]
Thanks for setting up the pull.   I've started using the SmartThingsPublic folder, I'll eventually switch my original post in the forums over to that (but for now your change has made this folder structure compliant).  I also need to integrate the battery reporting fix that was posted later in the forum thread.   Been busy with work and the holidays, but I should have time to work on this some after Christmas.
