### ISSUE TITLE
Smoke Alarm interconnectivity

### ISSUE THREAD

**Issue by snakedog116** [noname4444/smartthings#4]
Do you know if there's a way to program the smoke alarms to act as bells?

Then a smartApp could be created that if one goes off they all go off. (or it could be used for an alarm, if there's an intruder they start ringing etc.)

**Comment by noname4444** [comment]
While this is a really neat idea, unfortunately it will not work in practice.  The smoke detectors use a special low-power mode where they are "asleep" for most of the time, and occasionally "wake up" to see if there are any new commands.   Thus even if you could send the signal for an alarm, it wouldn't go off right away.

**Comment by snakedog116** [comment]
Interesting, any idea how the 'association' method works? I thought this meant that the detectors would ring each other. Which would not be possible while in this 'low power' mode.

Or, if SmartThings can't monitor the devices, do you know if the smoke alarms can be both in 'associated' mode so they communicate with each other, and also connected to z-wave, SmartThings at the same time?

http://downloads.monoprice.com/files/manuals/10797_Manual_131204.pdf

Thanks for looking into this.

**Comment by noname4444** [comment]
Hmm...  the manual says the "smoke" event is sent to all detectors that are associated with each other, but I don't see how the sleeping devices will receive it.  Either the battery or my detector is dead.  If it's the former, once I get a new battery I can try playing with this a bit.
